### ISSUE TITLE
Python import error when running simulation

### ISSUE THREAD

**Issue by archie1983** [arthurrichards77/farscope_group_project#10]
When I launch the simulation command:
`roslaunch farscope_group_project farscope_example_robot_simulate.launch`

I get the following error:
`
Traceback (most recent call last):
  File "/home/arturs/Desktop/Robotics/Group_project/noetic_workspaces/ae_farscope_group_project/devel/lib/farscope_group_project/test_pickup.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/arturs/Desktop/Robotics/Group_project/noetic_workspaces/ae_farscope_group_project/src/farscope_group_project/scripts/example/test_pickup.py", line 3, in <module>
    from move_arm import ArmMover
ImportError: cannot import name 'ArmMover' from 'move_arm' (/home/arturs/Desktop/Robotics/Group_project/noetic_workspaces/ae_farscope_group_project/devel/lib/farscope_group_project/move_arm.py)

[robot_controller-11] process has died [pid 687783, exit code 1, cmd /home/arturs/Desktop/Robotics/Group_project/noetic_workspaces/ae_farscope_group_project/devel/lib/farscope_group_project/test_pickup.py __name:=robot_controller __log:=/home/arturs/.ros/log/c05b89f2-6f06-11eb-aa32-315dbacfa70a/robot_controller-11.log].
log file: /home/arturs/.ros/log/c05b89f2-6f06-11eb-aa32-315dbacfa70a/robot_controller-11*.log
`

The effect is that the simulation starts, but nothing really happens- the robot stays in the starting position and never moves. This didn't happen in ROS Melodic on Ubuntu 18.04, but is a problem now after I upgraded to ROS Noetic on Ubuntu 20.04.

**Comment by arthurrichards77** [comment]
I think this is something to do with the CMakeLists.txt set-up.  I haven't got it formally exporting those Python modules as they also function as utility scripts to experiment with nudging the robot around.  However, like the indent issue, I suspect other versions of ROS and Python are fussier about finding the modules in the proper location.  Might take a little time to fix as I don't immediately have the set-up to recreate it, but I'll keep you posted.

**Comment by arthurrichards77** [comment]
Fixed - the relevant Python capabilities are now built into a common library [farscope_robot_utils](https://github.com/arthurrichards77/farscope_group_project/blob/main/src/farscope_group_project/farscope_robot_utils.py) that is exported in the proper manner, following [this process](https://roboticsbackend.com/ros-import-python-module-from-another-package/).  Tested on Noetic and all the utilities and [test_pickup](https://github.com/arthurrichards77/farscope_group_project/blob/main/scripts/example/test_pickup.py) work fine.  Haven't tested on Melodic at this time.
